wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: on #prevents full scan of Wi-Fi airspace before connection
  ap:
    password: ${backup_ap_password}
captive_portal:

esphome:
  name: ${name}

esp8266:
  board: esp01_1m
  restore_from_flash: True #restores state from flash on power off or update reboot

logger:

# Enable Home Assistant API
# Bypassing encryption for this as its all local
api:

# Enable over the air updates
ota:
  password: ${ota_password}

# Device Specific Config
uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  - platform: cse7766
    current:
      name: "${friendly_name} Current"
      accuracy_decimals: 1
    voltage:
      name: "${friendly_name} Voltage"
      accuracy_decimals: 1
    power:
      name: "${friendly_name} Power"
      accuracy_decimals: 1
      id: my_power
  - platform: total_daily_energy
    name: "${friendly_name} Daily Energy"
    power_id: my_power

switch:
  - platform: gpio
    name: "${friendly_name} Switch"
    pin: GPIO12
    id: relay

time:
  - platform: sntp
    id: my_time

status_led:
  pin: GPIO13